[theme]
base = "light"
primaryColor = "#1B1F3B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F3F5"
textColor = "#1B1F3B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
